apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: jaeger
    death-star-project: social-network
  name: jaeger-out
  namespace: social-network
spec:
  ports:
  - nodePort: 32000
    port: 16686
  selector:
    app-name: jaeger
    death-star-project: social-network
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: jaeger
    death-star-project: social-network
  name: jaeger-agent
  namespace: social-network
spec:
  ports:
  - name: udp1
    port: 5775
    protocol: UDP
  - name: tcp1
    port: 5778
  - name: udp2
    port: 6831
    protocol: UDP
  - name: udp3
    port: 6832
    protocol: UDP
  - name: tcp2
    port: 14250
  - name: tcp3
    port: 14268
  selector:
    app-name: jaeger
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: jaeger
    death-star-project: social-network
  name: jaeger-agent
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: jaeger
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: jaeger
        death-star-project: social-network
      name: jaeger-agent
    spec:
      containers:
      - env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: '9411'
        - name: JAEGER_AGENT_PORT
          value: '6831'
        image: jaegertracing/all-in-one:latest
        imagePullPolicy: IfNotPresent
        name: jaeger
      nodeName: skv-node3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: media-mongodb
    death-star-project: social-network
  name: media-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    app-name: media-mongodb
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: media-mongodb
    death-star-project: social-network
  name: media-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: media-mongodb
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: media-mongodb
        death-star-project: social-network
      name: media-mongodb
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Never
        name: media-mongodb
      nodeName: skv-node3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: post-storage-mongodb
    death-star-project: social-network
  name: post-storage-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    app-name: post-storage-mongodb
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: post-storage-mongodb
    death-star-project: social-network
  name: post-storage-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: post-storage-mongodb
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: post-storage-mongodb
        death-star-project: social-network
      name: post-storage-mongodb
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Never
        name: post-storage-mongodb
      nodeName: skv-node3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: social-graph-mongodb
    death-star-project: social-network
  name: social-graph-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    app-name: social-graph-mongodb
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: social-graph-mongodb
    death-star-project: social-network
  name: social-graph-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: social-graph-mongodb
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: social-graph-mongodb
        death-star-project: social-network
      name: social-graph-mongodb
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Never
        name: social-graph-mongodb
      nodeName: skv-node4
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: url-shorten-mongodb
    death-star-project: social-network
  name: url-shorten-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    app-name: url-shorten-mongodb
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: url-shorten-mongodb
    death-star-project: social-network
  name: url-shorten-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: url-shorten-mongodb
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: url-shorten-mongodb
        death-star-project: social-network
      name: url-shorten-mongodb
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Never
        name: url-shorten-mongodb
      nodeName: skv-node4
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: user-mongodb
    death-star-project: social-network
  name: user-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    app-name: user-mongodb
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: user-mongodb
    death-star-project: social-network
  name: user-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: user-mongodb
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: user-mongodb
        death-star-project: social-network
      name: user-mongodb
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Never
        name: user-mongodb
      nodeName: skv-node4
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: user-timeline-mongodb
    death-star-project: social-network
  name: user-timeline-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    app-name: user-timeline-mongodb
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: user-timeline-mongodb
    death-star-project: social-network
  name: user-timeline-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: user-timeline-mongodb
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: user-timeline-mongodb
        death-star-project: social-network
      name: user-timeline-mongodb
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Never
        name: user-timeline-mongodb
      nodeName: skv-node4
      restartPolicy: Always

